### ISSUE TITLE
rpcclient: file collision with samba-4.18.8

### ISSUE THREAD

**Issue by blshkv** [doronz88/pycrashreport#20]
https://github.com/doronz88/pycrashreport/blob/ba5613d5d1e2f8d4b33b6ae78bae9579ff9ee57d/pyproject.toml#L35

both packages install "/usr/bin/rpcclient".

Please rename this binary to something else.

**Comment by doronz88** [comment]
Thanks for reporting! this was unintentional.
Will very quickly release a new version with the fix

**Comment by blshkv** [comment]
Great, thanks. Could you fix for your other projects too? ipsw_parser, may be others

**Comment by doronz88** [comment]
Sure. Only just now I noticed i haven't refactored this part of my toml when copying it as a template
